name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Install Serverless Framework
      run: npm install -g serverless
        
    - name: Deploy to AWS Lambda
      run: |
        serverless deploy --verbose \
          --param="MYSQL_HOST=${{ secrets.MYSQL_HOST }}" \
          --param="MYSQL_USER=${{ secrets.MYSQL_USER }}" \
          --param="MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" \
          --param="MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" \
          --param="MYSQL_PORT=${{ secrets.MYSQL_PORT }}"
        
    - name: Cleanup .env file
      if: always()
      run: |
        rm -f .env